
services:

  bottle-filling_machine:
    #image: paradoxxs/virtuaplant:machine
    image: virtuaplant:hmi
    ports:
      - 5020:5020
      - 3001:3000
    networks:
      - OT
  bottle-filling_eng:
    #image: paradoxxs/virtuaplant:engineer
    image: virtuaplant:plc
    environment:
      - PLC_SERVER_IP=bottle-filling_machine
      - PLC_SERVER_PORT=502
    ports:
      - 3002:3000
    networks:
      - OT
    depends_on:
      - bottle-filling_machine
networks:

  OT:
    driver: bridge