
services:

  bottle-filling_plc:
    #image: paradoxxs/virtuaplant:plc
    image: virtuaplant:plc
    ports:
      - 5020:5020
      - 3001:3000
  bottle-filling_hmi:
    #image: paradoxxs/virtuaplant:hmi
    image: virtuaplant:hmi
    environment:
      - PLC_SERVER_IP=bottle-filling_plc
      - PLC_SERVER_PORT=5020
    ports:
      - 3002:3000
    depends_on:
      - bottle-filling_plc

      
networks:
 default:
   name: OT
   external: false